[Doc] Use substrate-ssvm docker image.
second-state/substrate-ssvm-node pull request #6
Opened 2020-06-04 03:22 UTC by dm4

2020-06-04 10:02 UTC, hydai requested changes
Please add our demo video.

2020-06-04 10:08 UTC, hydai approved these changes
LGTM

2020-06-04 10:50 UTC, CaptainVincent commented on README.md
>  5. Extend [command line tool](https://github.com/second-state/substrate-cli-tools) for support substrate-ssvm-node just like evm pallet did.
Help me plus `s` after tool.

2020-06-04 10:53 UTC, CaptainVincent commented on README.md
> +  - [Demo video](https://drive.google.com/open?id=119L2oCVuaGAZJ1yQj3YVsKAepc0DcFq-)
personal suggestion format.
- Use command line tools
   - [Demo video](https://drive.google.com/open?id=149AgZkvXeQZEAlZlNQ7bcZ8V2zCjpQf6)
   - [Doc](./docs/interact-using-cli.md)
 - Use Substrate web interface
   - [Demo video](https://drive.google.com/open?id=119L2oCVuaGAZJ1yQj3YVsKAepc0DcFq-)
   - [Doc](./docs/interact-using-web.md)

2020-06-04 11:26 UTC, CaptainVincent commented on docs/interact-using-cli.md
> +```bash
Maybe here need annotations execute inside node/substrate-ssvm-node folder. 
(Discontinuous with before command)

2020-06-04 14:45 UTC, CaptainVincent commented on docs/interact-using-web.md
> +  cargo run --release --bin node-template -- --dev
Does here need add `--ws-external`?

2020-06-05 03:54 UTC, dm4 commented on README.md
>  5. Extend [command line tool](https://github.com/second-state/substrate-cli-tools) for support substrate-ssvm-node just like evm pallet did.
ok

2020-06-05 03:55 UTC, dm4 commented on README.md
> +  - [Demo video](https://drive.google.com/open?id=119L2oCVuaGAZJ1yQj3YVsKAepc0DcFq-)
good suggestion!

2020-06-05 03:56 UTC, dm4 commented on docs/interact-using-cli.md
> +```bash
sure

2020-06-05 03:57 UTC, dm4 commented on docs/interact-using-web.md
> +  cargo run --release --bin node-template -- --dev
yes, I missed that QQ

2020-06-05 04:09 UTC, CaptainVincent commented
LGTM.

2020-06-05 04:10 UTC, merged